{"timestamp": "2025-05-23T05:20:49.200195", "level": "ERROR", "name": "myslt.api", "message": "SLT API login failed", "module": "api", "function": "login", "line": 101, "process_id": 58499, "thread_id": 8351991872, "exception": {"type": "HTTPError", "message": "503 Server Error: Service Unavailable for url: https://omniscapp.slt.lk/mobitelint/slt/api/Account/Login", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/himasha/Desktop/Projects/MySLT_Bot/myslt/api.py\", line 73, in login\n    response.raise_for_status()\n", "  File \"/Users/himasha/.pyenv/versions/3.9.16/lib/python3.9/site-packages/requests/models.py\", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n", "requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://omniscapp.slt.lk/mobitelint/slt/api/Account/Login\n"]}}
{"timestamp": "2025-05-23T05:20:49.201568", "level": "CRITICAL", "name": "commands.general", "message": "Failed to initialize SLTAPI", "module": "general", "function": "<module>", "line": 17, "process_id": 58499, "thread_id": 8351991872, "exception": {"type": "Exception", "message": "Login failed: 503 Server Error: Service Unavailable for url: https://omniscapp.slt.lk/mobitelint/slt/api/Account/Login", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/himasha/Desktop/Projects/MySLT_Bot/myslt/api.py\", line 73, in login\n    response.raise_for_status()\n", "  File \"/Users/himasha/.pyenv/versions/3.9.16/lib/python3.9/site-packages/requests/models.py\", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n", "requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://omniscapp.slt.lk/mobitelint/slt/api/Account/Login\n", "\nDuring handling of the above exception, another exception occurred:\n\n", "Traceback (most recent call last):\n", "  File \"/Users/himasha/Desktop/Projects/MySLT_Bot/commands/general.py\", line 14, in <module>\n    slt_api = SLTAPI(USERNAME, PASSWORD)\n", "  File \"/Users/himasha/Desktop/Projects/MySLT_Bot/myslt/api.py\", line 34, in __init__\n    self.login()  # Automatically login on initialization\n", "  File \"/Users/himasha/Desktop/Projects/MySLT_Bot/myslt/api.py\", line 111, in login\n    raise Exception(f\"Login failed: {str(e)}\")\n", "Exception: Login failed: 503 Server Error: Service Unavailable for url: https://omniscapp.slt.lk/mobitelint/slt/api/Account/Login\n"]}}
{"timestamp": "2025-05-23T05:24:58.608165", "level": "ERROR", "name": "myslt.api", "message": "SLT API login failed", "module": "api", "function": "login", "line": 101, "process_id": 59341, "thread_id": 8351991872, "exception": {"type": "HTTPError", "message": "401 Client Error: Unauthorized for url: https://omniscapp.slt.lk/slt/ext/api/Account/Login", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/himasha/Desktop/Projects/MySLT_Bot/myslt/api.py\", line 73, in login\n    response.raise_for_status()\n", "  File \"/Users/himasha/.pyenv/versions/3.9.16/lib/python3.9/site-packages/requests/models.py\", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n", "requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://omniscapp.slt.lk/slt/ext/api/Account/Login\n"]}}
{"timestamp": "2025-05-23T05:24:58.610564", "level": "CRITICAL", "name": "commands.general", "message": "Failed to initialize SLTAPI", "module": "general", "function": "<module>", "line": 17, "process_id": 59341, "thread_id": 8351991872, "exception": {"type": "Exception", "message": "Login failed: 401 Client Error: Unauthorized for url: https://omniscapp.slt.lk/slt/ext/api/Account/Login", "traceback": ["Traceback (most recent call last):\n", "  File \"/Users/himasha/Desktop/Projects/MySLT_Bot/myslt/api.py\", line 73, in login\n    response.raise_for_status()\n", "  File \"/Users/himasha/.pyenv/versions/3.9.16/lib/python3.9/site-packages/requests/models.py\", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n", "requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://omniscapp.slt.lk/slt/ext/api/Account/Login\n", "\nDuring handling of the above exception, another exception occurred:\n\n", "Traceback (most recent call last):\n", "  File \"/Users/himasha/Desktop/Projects/MySLT_Bot/commands/general.py\", line 14, in <module>\n    slt_api = SLTAPI(USERNAME, PASSWORD)\n", "  File \"/Users/himasha/Desktop/Projects/MySLT_Bot/myslt/api.py\", line 34, in __init__\n    self.login()  # Automatically login on initialization\n", "  File \"/Users/himasha/Desktop/Projects/MySLT_Bot/myslt/api.py\", line 111, in login\n    raise Exception(f\"Login failed: {str(e)}\")\n", "Exception: Login failed: 401 Client Error: Unauthorized for url: https://omniscapp.slt.lk/slt/ext/api/Account/Login\n"]}}
